### ISSUE TITLE
Failed to add apple id

### ISSUE THREAD

**Issue by infinite-dev22** [Odevio/Odevio-CLI#47]
I tried to add my apple id and it failed. Says the Mac has had many apple ids and I have to contat apple to add a new ID

**Comment by tchavetdeuse** [comment]
Hi did you get this error trying to add the apple ID inside the mac vm? Apple does not allow login inside a VM unfortunately

**Comment by tchavetdeuse** [comment]
Why do you need to login? Maybe we can add the feature you're missing without needing to login

**Comment by infinite-dev22** [comment]
I want to publish my application to apple store through Odevio

**Comment by tchavetdeuse** [comment]
You need to start a publication build then, not a configuration one. Odevio will take care of the certificate and publication.

**Comment by infinite-dev22** [comment]
I am using the GUI not the cli, and the GUI requires an application(which requires a developer id to be add when creating one) for build types other than configuration

**Comment by infinite-dev22** [comment]
I get you clearly, then why add buildtypes that require the developer account

**Comment by infinite-dev22** [comment]
> but for that Odevio needs your developer account.
Which I am not being able to add in the GUI app. On CLI, I tried and was getting the same error.

**Comment by maxcmoi89** [comment]
Can you make a screenshot of the error message you get when adding your Developer account to the CLI ou GUI app of Odevio ?
